server.port: 8888

---
spring.profiles: test_linux
Bach.chorale.path: /home/night_wish/Music/Bach chorals cut/
---
spring.profiles: test_win
Bach.chorale.path: /home/night_wish/Music/Bach chorals cut/
---
spring.profiles: prod
Bach.chorale.path: /home/pavel/Music/Back chorale