build.version: '@project.version@'

composer:
  pathToCompositions: Path to folder, containing compositions that would be decomposed used in new piece creation, for example "../Bach chorals cut/"

persistance:
  file: input/bach-full.db

server:
  port: 8888

spring:
  application:
    name: MusicComposer

melodyFormEqualityAnalyzer:
  equalityTestPassThreshold: 0.45

formEquality:
  instrumentEqualityPassThreshold: 0.7
  instrumentEqualityFailThreshold: 0.4
