build.version: '@project.version@'

composer:
  pathToCompositions: Path to folder, containing compositions that would be decomposed used in new piece creation, for example "../Bach chorals cut/"

persistance:
  file: Path to db file, for example bach-prod.db

server:
  port: 8888

spring:
  application:
    name: MusicComposer

MelodyFormEqualityAnalyzer:
  equalityTestPassThreshold: 0.45

FormEquality:
  instrumentEqualityPassThreshold: 0.7
  instrumentEqualityFailThreshold: 0.4