version: "3.8"

services:
  music-composer-server:
    image: roasher/ru.yurkins-workshop.music-composer-server:1.0-SNAPSHOT
    environment:
      spring_profiles_active: bach
      persistance_file: /bach-full.db
    volumes:
      - /Users/pavelyurkin/Documents/music_composer_db/bach-full.db:/bach-full.db
    ports:
      - "8888:8888"
    deploy:
      resources:
        limits:
          memory: 4G
  music-composer-web-front:
    image: roasher/ru.yurkins-workshop.music-composer-web:0.0.2
    ports:
      - "8080:8080"