spring:
  datasource:
    url: jdbc:h2:file:/home/pyurkin/Music//prod;AUTO_SERVER=TRUE

persistance:
  file: /home/pyurkin/Music//bach-prod.db

composer:
  pathToCompositions: /home/pyurkin/Music/Database/Test/Bach chorals/