persistance:
  file: /home/pyurkin/Music//mozart-test.db

composer:
  pathToCompositions: /home/pyurkin/Music/Database/Test/Classical music/mozart/

logging:
  level:
    ru.pavelyurkin.musiccomposer.core: debug