persistance:
  file: /home/pyurkin/Music//bach-test.db

composer:
  pathToCompositions: /home/pyurkin/Music/Database/Test/Bach chorals cut/

logging:
  level:
    ru.pavelyurkin.musiccomposer.core: debug