persistance:
  file: D:\Programming\music\musiccomposer\bach-prod.db

composer:
  pathToCompositions: D:\YandexDisk\Music\Algorithmic music\Database\Test\Bach chorals

logging:
  level:
    ru.pavelyurkin.musiccomposer.core: debug