build.version: @project.version@

spring:
  datasource:
    url: jdbc:h2:~/prod;AUTO_SERVER=TRUE
    username: sa
  jpa.hibernate.ddl-auto: update

MelodyFormEqualityAnalyzer.equalityTestPassThreshold: 0.45
FormEquality.instrumentEqualityPassThreshold: 0.7
FormEquality.instrumentEqualityFailThreshold: 0.4

logging:
  level:
    ru.pavelyurkin.musiccomposer.core.decomposer.SignatureDecomposer: DEBUG
    ru.pavelyurkin.musiccomposer.core.decomposer.melody.analyzer.MelodyEqualityAnalyzerImpl: DEBUG
    ru.pavelyurkin.musiccomposer.core.composer.CompositionComposer: DEBUG
    ru.pavelyurkin.musiccomposer.core.composer.FormBlockProvider: DEBUG
    ru.pavelyurkin.musiccomposer.core.equality.form.FormEquality: DEBUG